### PR TITLE
XML Parser to handle incorrect casing in about.xml

### LINKED ISSUE #134: Server can't load mod, The following modes are conflicting with the server.
【My English is so poor, so I used machine translation. Please understand.】
Today, when I was configuring mods for Rimworld Together, I found that the server couldn't load the mods.  So, I reinstalled the game and updated the mods, but it still couldn't load them. Then I found the problem in the "About.xml" file of the mod that couldn't be loaded.
After accidentally deleting a "<", I noticed that the server read the file and returned an error.   So, I compared this file with the "About.xml" files of other mods that could be read normally, and found that the unreadable "About.xml" used "<modMetaData></modMetaData>", while the readable ones used "<ModMetaData></ModMetaData>".
So, I changed it to start with a capital letter, and then the mod could be read normally.
Maybe could consider fixing this?

### PR DESCRIPTION
**Pull request by nightred**
This changes the XML parser to handle tags in any case.
Resolves issues around mod authors not using proper formatting on XML tags.

Made the search for the about file ignore the case of the about file.
This will now load AbOUt.Xml without issue.

Some minor changes to early escape on functions.

Fixes: #134

### CODE REVIEW

**Review by Byte-Nova — CHANGES_REQUESTED** [review]
With the current implementation of this PR, the server is unable to load any mod whatsoever from my testing. Not sure where the error might be located.

**Comment by nightred** [comment]
Interesting I will update when fixed.

**Comment by nightred** [comment]
Tested, mods load and XML tags are now case Insensitive

```
[08:31:14] | File > 'X:\Rimworld-Together\Source\Server\bin\Debug\net7.0\Mods\Required\Anomaly\About\about.xml'
[08:31:14] | Loaded > 'X:\Rimworld-Together\Source\Server\bin\Debug\net7.0\Mods\Required\Anomaly > 'ludeon.rimworld.anomaly'
[08:31:14] | File > 'X:\Rimworld-Together\Source\Server\bin\Debug\net7.0\Mods\Required\Biotech\About\abOUT.xml'
[08:31:14] | Loaded > 'X:\Rimworld-Together\Source\Server\bin\Debug\net7.0\Mods\Required\Biotech > 'ludeon.rimworld.biotech'
```

**Comment by Byte-Nova** [comment]
Got it, will test tomorrow and if everything is right push it as well

**Review by Byte-Nova — APPROVED** [review]

**Pull request merged**
