### PR TITLE
jrseducate Updates [Plugins, Item Components Mapper, Sync Settlements Command]

### PR DESCRIPTION
**Pull request by jrseducate**
** Server Plugins **
 - Added Server Plugins to allow more flexibility in server functionality
 - Included 2 plugins to start:
  * Example: A basic example plugin doing bare-minimum documenting basic concepts in plugin development
  * Autosave: An autosave plugin that requests all players save on a given interval, then backs up the relevant files into a zip for long-term backups

** Item Scribe Components Mapper **
 - Added mapper utility to easily generate mapped properties of components on items being sent
 - Mapped 1 component to start:
  * CompPowerBattery: All battery related devices will now retain their charged power percentage

** Minor Additions **
 - Save messages have been added to indicate when saves have occured and have been succesfully sent to the server (option available in mod settings)
 - 'syncsettlements [player name]' command utility added to help fix any settlements not currently in-server, or any settlements in-server that are no longer local
 - Commented out EventManager::SendEvent() [target.inSafeZone] logic temporarily, there is no updates made to the value once it's set to true forcing players to log out and back in to send more than a single event

** Small Bugfix (5/16/2024) **
- Added proper check to isReadyToPlay for Autosave plugin, had an issue where the Autosave would be triggered mid-loading of a save causing an issue where the client is disconnected from the server, but continues to play in their save

### CODE REVIEW

**Comment by AnauNaga** [comment]
I would keep changes in separate pull requests. Having multiple separate changes and continuing to add things is going to make it harder to test. i.e. the plugin stuff should be kept in a separate pull request from item components

**Comment by jrseducate** [comment]
My bad, I'll keep those features separate in the future, I can split them out into two separate PRs if that would help

**Comment by AnauNaga** [comment]
I should also note that our use of json is very misleading. There are a lot of variables and functions that have json in the name, but they have nothing to do with json at all. For example the Packet::CreatePacketFromJSON() has nothing to do with JSON files, it just serializes objects. This is because files used to be sent as jsons, but switched to a binary serialization, and recently all the files in PacketData used to be named as json, but a recent PR fixed that. Theres no need to change how the component mapper serializes data, but if you want to try to keep it consistent with how everything else serializes, it would be helpful. 

The message for syncing with the server is a good idea, and its something thats been on my priority list. I think it should be flipped, though. Rimworld has a special window for when the game is saving that we could take advantage of. I believe its called with the long event handler. Then, if the game throws an exception we can display a message for the error instead. I'm just thinking that needing to click ok every time the game saves would become tiresome. (i'm assuming the message window has an 'ok' button, i've never used it)

I havent had a chance to really test the code, but it looks solid.

**Comment by jrseducate** [comment]
I like that, I think I've seen that window as well. I'll take some time to look into it and see what we can do.

The json stuff I can definitely adjust to use binary serialization, ngl some of it was kinda quick and dirty. I wrote a lot of this while playing with a friend of mine so I was just trying to get it up and running lol.

Thank you, glad to hear it looks solid. 
Btw the messages that are shown aren't actually in a dialog right now, I have them showing on those lil messages that pop up top-left on screen

**Comment by AnauNaga** [comment]
You should definitelly join the contributors role on the discord server. We talk about the direction of the mod. It would also help to know what changes people are already working on

**Comment by jrseducate** [comment]
I'd like that 👍, my Discord user is [FuchsiaDaddy] for anyone interested in contacting me

**Comment by Byte-Nova** [comment]
Putting this into low priority for now because it's been left out for a while and the code probably needs some extra love to be compatible for merge.

**Comment by Byte-Nova** [comment]
Closing due to inactivity and deprecation

**Pull request closed without merging**
