### PR TITLE
Disconnect prompt to save locally

### PR DESCRIPTION
**Pull request by Fokson**
When losing connection to a server, the game will ask if you'd like to save locally before returning to the title screen to avoid loss of progress.

### CODE REVIEW

**Review by Byte-Nova — CHANGES_REQUESTED** [review]
Found the following issues while testing the PR:
- [ ] The new disconnect dialog is too long and doesn't fit in the window frame.
- [ ] Trying to save locally when the connection is dropped will make it so you won't be able to join servers anymore.

**Comment by davidfleming** [comment]
If it saves locally it will still be overwritten with the remove version the next time you join a server.

**Comment by Fokson** [comment]
@davidfleming That's irrelevant; the if the server crashes and would have destroyed 3 days of someone's progress anyway, it at least gives the option for the user to send their preserved progress to the server owner.

**Comment by davidfleming** [comment]
@Fokson It's not irrelevant.   It's not intuitive.  Users won't know to do this and they shouldn't be expected to manually copy save files and send them to an owner.

**Comment by AnauNaga** [comment]
@davidfleming This PR does not represent the entirety of an idea,
but rather is the first step to solving issues around disconnections before the game is saved.
After this PR, the next step would be coming up with a safe way to
allow players to send a save to the server through in-game menus.
This PR is more useful existing than having nothing at all.

**Comment by davidfleming** [comment]
@AnauNaga The dialog will be confusing to your average player.  The dialog should be modified to say that it requires manually sending the save or it will be overwritten.  Otherwise you will have a lot of people asking why they still lost their save when they rejoin the server.

**Comment by davidfleming** [comment]
I've gone ahead and opened up another PR that fixes the bugs with this one, as well as facilitates using the latest save automatically, by having the client compare the save it gets from the server vs the save it has locally, and fixed the connection bugs.

https://github.com/RimworldTogether/Rimworld-Together/pull/105

**Comment by Byte-Nova** [comment]
Closing this PR because it's near identical to #105 and that one got pulled

**Pull request closed without merging**
