### PR TITLE
Changing strings to keyed to allow Translation

### PR DESCRIPTION
**Pull request by SimobiSirOP**
### Short and concise description about my pull request:

- This pull request will allow translation of entire Rimworld Together.

### TODOs:

- [x] - I confirm this PR has been previously tested by me and has no apparent issues.
- [ ] - I confirm this PR is complying with this project's [Contribution Guidelines](https://github.com/RimworldTogether/Rimworld-Together/blob/development/.github/CONTRIBUTING.md).
- [ ] - I confirm this PR is complying with this project's [Syntax Ruleset](https://github.com/RimworldTogether/Rimworld-Together/blob/development/.github/SYNTAX.md).

### Contributing:

- This PR implements a translation change.
      
Because it's a translation change, there isn't any need in Guide changes

### Longer / More informative description about what my pull request does:

- Currently, we have a lot of hardcoded text in your Code. This PR changes every string, that players will see in their game(Without changes to Log Messages) to Verse strings. This will allow translation of almost every thing.

Fixes: #143

### CODE REVIEW

**Comment by SimobiSirOP** [comment]
Not really good in C#, so sometimes it looks strange.

**Comment by Byte-Nova** [comment]
@SimobiSirOP Whenever you are able to, please move the target branch from development to translations, since that's the one where this kind of implementations go first.

**Comment by SimobiSirOP** [comment]
If merged, this will also put upstream into translations branch

**Comment by SimobiSirOP** [comment]
Tested Market, Road Building, Transfers, Factions, Configs, GoodWill, works fine for me

**Comment by SimobiSirOP** [comment]
Changed PR description to new PR template

**Comment by SimobiSirOP** [comment]
Will add example of how its works(and also to make PR alive

<RTMeow>Meow<RTMeow>

**Comment by SimobiSirOP** [comment]
No new commits in 2 days, so i will make a comment about fixing merge conflicts (I'm smart :))

**Comment by SimobiSirOP** [comment]
Also, if someone wants to test this PR, i made a Russian translation for testing purposes, it's on a different branch. [https://github.com/SimobiSirOP/Rimworld-Together/tree/Testing](url)

**Comment by SimobiSirOP** [comment]
Getting back.

**Comment by SimobiSirOP** [comment]
?

**Comment by SimobiSirOP** [comment]
Already made new pull request #207

**Pull request closed without merging**
